### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by sdarwin** [livinginthepast/ipaddr_extensions#1]
Hi,
When installing the cookbook with chef 12.4.1 for the first time there are compile errors.   It doesn't appear to finish.    It crashes.   On the second run, it's ok.      Is this because the cookbook, per the readme file, "does terrible things", and so  this is sort of an expected result, and can't really be fixed?

Fetching: ipaddr_extensions-1.0.2.gem (100%)
# ================================================================================

Recipe Compile Error in /root/.chef/local-mode-cache/cache/cookbooks/ipaddr_extensions/libraries/gem_installation.rb
# ================================================================================

LoadError
# ---------

cannot load such file -- ipaddr_extensions

**Comment by sax** [comment]
This has to do with the version of rubygems used. I'm currently trying to find a way around this issue.
- rubygems 2.2.2 : LoadError is caught, gem gets installed
- rubygems 2.4.8 : LoadError is caught, then re-raised in Gem.install

**Comment by sax** [comment]
This is fixed on master in rubygems (https://github.com/rubygems/rubygems/issues/1315, https://github.com/rubygems/rubygems/pull/1282), but I'm going to push a fix to keep this from breaking chef runs.

**Comment by sax** [comment]
I just pushed a new version to supermarket, if you want to try it out.
